### ISSUE TITLE
Gerenciar alarmes - Tela

### ISSUE THREAD

**Issue by MatheusAraujo6** [MatheusAraujo6/pimobile3a#15]

**Comment by Facosao** [comment]
Esta tela lista todos os alarmes criados, permite ativar/desativar cada alarme de maneira rápida e permite adicionar ou remover alarmes.

**Comment by MatheusAraujo6** [comment]
![Image](https://user-images.githubusercontent.com/107648001/230904415-1f0ad097-4365-4ae0-aff9-33b765ef703c.png)
