### ISSUE TITLE
Editar alarme - Tela

### ISSUE THREAD

**Issue by MatheusAraujo6** [MatheusAraujo6/pimobile3a#17]

**Comment by Facosao** [comment]
Esta tela permite editar as configurações de um alarme, como:
- Nome do alarme;
- Hora para despertar;
- Padrão de repetição do alarme (toda segunda, a cada 3 dias, a cada semana, etc.);
- Toque musical escolhido para o alarme;
- Volume do alarme

**Comment by Facosao** [comment]
![Image](https://user-images.githubusercontent.com/111313085/235519961-c361ac93-52d2-431c-8bde-0c2224137e10.png)
